; Neon Stadium: an original eight-bar, 128 BPM arena-rave signal demo.
; The SPU only schedules a generic g.* kernel. Guest instructions implement
; seven polyBLEP-corrected detuned saws, gated bass/chords, avalanche noise,
; kick, snare, offbeat hats, envelopes, ducking, and stereo float stores.
; The CPU paints a small indexed visual and animates one scanline at vblank.
.profile spu-1
.equ SPU, 0xf6000
.equ VIDEO, 0xf5000
.equ FB, 0x10000
.equ PAL, 0x20000
.equ AUDIO, 0x24000
.entry start

start:
    li r12, SPU
    li r1, sound_kernel
    sw r1, 0x40(r12)
    li r1, sound_kernel_end-sound_kernel
    sw r1, 0x44(r12)
    li r1, 128
    sw r1, 0x48(r12)
    li r1, 2
    sw r1, 0x4c(r12)
    li r1, AUDIO
    sw r1, 0x50(r12)
    sw r1, 0x100(r12)       ; binding 0: 256 stereo f32 sample frames
    li r1, 2048
    sw r1, 0x104(r12)
    li r1, 3
    sw r1, 0x108(r12)
    li r1, sound_tables
    sw r1, 0x110(r12)       ; binding 1: counted ROM wavetables/notes
    li r1, sound_tables_end-sound_tables
    sw r1, 0x114(r12)
    li r1, 1
    sw r1, 0x118(r12)
    sw r1, 0(r12)           ; enable audio before visual setup

    ; A 256-colour blue-to-coral palette, generated by the guest CPU.
    li r2, PAL
    mov r3, r0
    li r4, 256
    li r5, 1
palette_loop:
    addi r6, r3, 24
    sb r6, 0(r2)
    shr r7, r3, r5
    addi r7, r7, 70
    sb r7, 1(r2)
    sub r8, r4, r3
    sb r8, 2(r2)
    addi r2, r2, 3
    addi r3, r3, 1
    bltu r3, r4, palette_loop

    ; Interference stripes and a bright centre band in the I8 framebuffer.
    li r2, FB
    mov r3, r0             ; y
    li r10, 120
    li r11, 160
paint_row:
    mov r4, r0             ; x
paint_pixel:
    li r5, 2
    shl r6, r3, r5
    xor r6, r6, r4
    andi r6, r6, 127
    li r5, 52
    bltu r3, r5, paint_store
    li r5, 68
    bltu r3, r5, paint_centre
    j paint_store
paint_centre:
    addi r6, r6, 90
paint_store:
    sb r6, 0(r2)
    addi r2, r2, 1
    addi r4, r4, 1
    bltu r4, r11, paint_pixel
    addi r3, r3, 1
    bltu r3, r10, paint_row

    li r9, VIDEO
    li r1, FB
    sw r1, 0(r9)
    li r1, 160
    sw r1, 4(r9)
    li r1, 3              ; I8, 256-colour palette
    sw r1, 8(r9)
    li r1, PAL
    sw r1, 12(r9)
    li r1, 1
    sw r1, 16(r9)
    sw r1, 20(r9)
    mov r8, r0             ; visual phase
visual_frame:
    wfi
    li r2, FB+9600        ; middle scanline, y=60
    mov r3, r0
    li r4, 160
visual_pixel:
    add r5, r3, r8
    andi r5, r5, 255
    sb r5, 0(r2)
    addi r2, r2, 1
    addi r3, r3, 1
    bltu r3, r4, visual_pixel
    addi r8, r8, 3
    j visual_frame

; Each invocation owns one stereo sample. All time is reduced modulo the
; exact eight-bar phrase (15 seconds at 128 BPM) before conversion to f32.
; The fixed 13-step reduction bounds phase math even late in a long playback.
; g1 phrase sample, g2 block invocation, g5 eighth index, g6 eighth phase,
; g7 eighth parity, g8 quarter index, g9 bar index; g18/g29 riff stereo,
; g19 bass, g20 kick, g21 snare, g22 hat, g23 chord, g11 duck factor.
sound_kernel:
    g.uniform g1, 14
    g.id g2, 2
    g.add g1, g1, g2
    g.li g30, 2949120000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_12
    g.sub g1, g1, g30
modulo_skip_12:
    g.li g30, 1474560000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_11
    g.sub g1, g1, g30
modulo_skip_11:
    g.li g30, 737280000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_10
    g.sub g1, g1, g30
modulo_skip_10:
    g.li g30, 368640000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_9
    g.sub g1, g1, g30
modulo_skip_9:
    g.li g30, 184320000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_8
    g.sub g1, g1, g30
modulo_skip_8:
    g.li g30, 92160000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_7
    g.sub g1, g1, g30
modulo_skip_7:
    g.li g30, 46080000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_6
    g.sub g1, g1, g30
modulo_skip_6:
    g.li g30, 23040000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_5
    g.sub g1, g1, g30
modulo_skip_5:
    g.li g30, 11520000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_4
    g.sub g1, g1, g30
modulo_skip_4:
    g.li g30, 5760000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_3
    g.sub g1, g1, g30
modulo_skip_3:
    g.li g30, 2880000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_2
    g.sub g1, g1, g30
modulo_skip_2:
    g.li g30, 1440000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_1
    g.sub g1, g1, g30
modulo_skip_1:
    g.li g30, 720000
    g.sltu g31, g1, g30
    g.bnz g31, modulo_skip_0
    g.sub g1, g1, g30
modulo_skip_0:
    g.itof g3, g1
    g.fli g24, 11250.0
    g.fdiv g4, g3, g24
    g.ftoi g5, g4
    g.itof g6, g5
    g.fsub g6, g4, g6
    g.li g24, 1
    g.and g7, g5, g24
    g.shr g8, g5, g24
    g.li g24, 3
    g.shr g9, g5, g24

    ; Each eighth holds frequency plus the note's start/duration metadata.
    ; Tied rows keep the same start, so phase never restarts mid-note.
    g.li g24, 3
    g.shl g27, g5, g24
    g.li g24, lead_riff-sound_tables
    g.add g27, g27, g24
    g.ld g10, g27, 1
    g.mov g18, g0
    g.mov g29, g0
    g.bz g10, lead_done
    g.li g24, 4
    g.add g27, g27, g24
    g.ld g14, g27, 1        ; start step in low byte, duration above it
    g.li g24, 8
    g.shr g26, g14, g24
    g.itof g26, g26         ; duration in eighth-note steps
    g.li g24, 255
    g.and g25, g14, g24
    g.itof g25, g25         ; event start in eighth-note steps
    g.fsub g12, g4, g25     ; elapsed note time, continuous across ties
    g.fmul g12, g12, g10   ; oscillator cycles since this event began
    g.fli g24, 11250.0
    g.fdiv g11, g10, g24     ; one-sample phase step
    g.mov g13, g0           ; detune record byte offset
    g.li g14, lead_riff-sound_tables
    g.li g23, 4
supersaw_voice:
    g.ld g15, g13, 1        ; detune ratio
    g.add g13, g13, g23
    g.ld g30, g13, 1        ; left weight
    g.add g13, g13, g23
    g.ld g31, g13, 1        ; right weight
    g.add g13, g13, g23
    g.ld g28, g13, 1        ; independent starting phase
    g.add g13, g13, g23
    g.fmul g16, g12, g15
    g.fadd g16, g16, g28
    g.ftoi g27, g16
    g.itof g27, g27
    g.fsub g16, g16, g27    ; fractional saw phase
    g.fmul g17, g11, g15    ; detuned phase step
    g.fli g28, 2.0
    g.fmul g24, g16, g28
    g.fli g28, 1.0
    g.fsub g24, g24, g28   ; naive saw 2p-1
    ; Guest polyBLEP removes the hard discontinuity over one sample step.
    g.flt g27, g16, g17
    g.bz g27, saw_high_edge
    g.fdiv g27, g16, g17
    g.fmul g28, g27, g27
    g.fadd g27, g27, g27
    g.fsub g27, g27, g28
    g.fli g28, 1.0
    g.fsub g27, g27, g28
    g.fsub g24, g24, g27
    g.jmp saw_mix
saw_high_edge:
    g.fli g28, 1.0
    g.fsub g27, g28, g17
    g.flt g27, g27, g16
    g.bz g27, saw_mix
    g.fli g28, 1.0
    g.fsub g27, g16, g28
    g.fdiv g27, g27, g17
    g.fmul g28, g27, g27
    g.fadd g27, g27, g27
    g.fadd g27, g27, g28
    g.fli g28, 1.0
    g.fadd g27, g27, g28
    g.fsub g24, g24, g27
saw_mix:
    g.fmul g27, g24, g30
    g.fadd g18, g18, g27
    g.fmul g27, g24, g31
    g.fadd g29, g29, g27
    g.sltu g27, g13, g14
    g.bnz g27, supersaw_voice
    ; Flat sustain. Attack ~5 ms; release only over the final ~30 ms.
    g.fsub g27, g4, g25
    g.fli g24, 46.875
    g.fmul g27, g27, g24
    g.fli g24, 1.0
    g.fmin g27, g27, g24
    g.fsub g28, g26, g4
    g.fadd g28, g28, g25
    g.fli g24, 0.128
    g.fdiv g28, g28, g24
    g.fmax g28, g28, g0
    g.fli g24, 1.0
    g.fmin g28, g28, g24
    g.fmul g27, g27, g28
    g.fli g24, 0.96        ; LEAD_GAIN
    g.fmul g27, g27, g24
    g.fmul g18, g18, g27
    g.fmul g29, g29, g27
lead_done:
    ; Quarter phase combines even/odd eighths; bass and kick end in silence.
    g.itof g24, g7
    g.fadd g24, g24, g6
    g.fli g27, 0.5
    g.fmul g24, g24, g27
    g.li g27, 2
    g.shl g27, g8, g27
    g.li g28, bass_line-sound_tables
    g.add g27, g27, g28
    g.ld g10, g27, 1
    g.mov g19, g0
    g.bz g10, bass_done
    g.fmul g12, g24, g10
    g.ftoi g13, g12
    g.itof g13, g13
    g.fsub g12, g12, g13
    g.fli g13, 0.5
    g.fsub g12, g12, g13
    g.fsub g13, g0, g12
    g.fmax g12, g12, g13
    g.fli g13, 4.0
    g.fmul g12, g12, g13
    g.fli g13, 1.0
    g.fsub g19, g13, g12    ; triangle bass
    g.fli g13, 60.0
    g.fmul g27, g24, g13
    g.fli g13, 1.0
    g.fmin g27, g27, g13
    g.fli g13, 0.82
    g.fdiv g28, g24, g13
    g.fli g13, 1.0
    g.fsub g28, g13, g28
    g.fmax g28, g28, g0
    g.fmul g28, g28, g28
    g.fmul g27, g27, g28
    g.fli g13, 0.24        ; BASS_GAIN
    g.fmul g27, g27, g13
    g.fmul g19, g19, g27
bass_done:
    ; Two-note chord stabs occur only on the offbeat eighths.
    g.mov g23, g0
    g.bz g7, chord_done
    g.li g27, 3
    g.shl g27, g9, g27
    g.li g28, chord_progression-sound_tables
    g.add g27, g27, g28
    g.ld g10, g27, 1
    g.li g28, 4
    g.add g27, g27, g28
    g.ld g11, g27, 1
    g.fmul g12, g6, g10
    g.ftoi g13, g12
    g.itof g13, g13
    g.fsub g12, g12, g13
    g.fli g13, 0.5
    g.fsub g12, g12, g13
    g.fsub g13, g0, g12
    g.fmax g12, g12, g13
    g.fli g13, 4.0
    g.fmul g12, g12, g13
    g.fli g13, 1.0
    g.fsub g23, g13, g12
    g.fmul g12, g6, g11
    g.ftoi g13, g12
    g.itof g13, g13
    g.fsub g12, g12, g13
    g.fli g13, 0.5
    g.fsub g12, g12, g13
    g.fsub g13, g0, g12
    g.fmax g12, g12, g13
    g.fli g13, 4.0
    g.fmul g12, g12, g13
    g.fli g13, 1.0
    g.fsub g12, g13, g12
    g.fadd g23, g23, g12
    g.fli g13, 45.0
    g.fmul g27, g6, g13
    g.fli g13, 1.0
    g.fmin g27, g27, g13
    g.fli g13, 0.73
    g.fdiv g28, g6, g13
    g.fli g13, 1.0
    g.fsub g28, g13, g28
    g.fmax g28, g28, g0
    g.fmul g28, g28, g28
    g.fmul g27, g27, g28
    g.fli g13, 0.075       ; CHORD_GAIN
    g.fmul g27, g27, g13
    g.fmul g23, g23, g27
chord_done:
    ; Four-on-the-floor pitch-swept kick. Its envelope also ducks music.
    g.fli g13, 0.38
    g.fdiv g12, g24, g13
    g.fli g13, 1.0
    g.fsub g12, g13, g12
    g.fmax g12, g12, g0
    g.fmul g12, g12, g12
    g.fli g13, 220.0
    g.fmul g27, g24, g13
    g.fli g13, 1.0
    g.fmin g27, g27, g13
    g.fmul g12, g12, g27   ; kick envelope
    g.fli g13, 0.42
    g.fmul g11, g12, g13
    g.fli g13, 1.0
    g.fsub g11, g13, g11   ; music duck factor
    ; 90 Hz down toward 30 Hz across a 128 BPM quarter note.
    g.fli g13, 42.1875
    g.fmul g13, g24, g13
    g.fmul g14, g24, g24
    g.fli g15, 14.0625
    g.fmul g14, g14, g15
    g.fsub g13, g13, g14
    g.ftoi g14, g13
    g.itof g14, g14
    g.fsub g13, g13, g14
    g.fli g14, 0.5
    g.fsub g13, g13, g14
    g.fsub g14, g0, g13
    g.fmax g13, g13, g14
    g.fli g14, 4.0
    g.fmul g13, g13, g14
    g.fli g14, 1.0
    g.fsub g20, g14, g13
    g.fmul g20, g20, g12
    g.fli g13, 0.34        ; KICK_GAIN
    g.fmul g20, g20, g13

    ; Two independent 32-bit avalanche hashes replace the correlated ramp
    ; of a simple LCG. Sum = low-pass snare, difference = high-pass hat.
    g.mov g27, g1
    g.li g31, 16
    g.shr g30, g27, g31
    g.xor g27, g27, g30
    g.li g31, 0x7feb352d
    g.mul g27, g27, g31
    g.li g31, 15
    g.shr g30, g27, g31
    g.xor g27, g27, g30
    g.li g31, 0x846ca68b
    g.mul g27, g27, g31
    g.li g31, 16
    g.shr g30, g27, g31
    g.xor g27, g27, g30
    g.li g31, 65535
    g.and g27, g27, g31
    g.itof g27, g27
    g.fli g31, 0.000030517578125
    g.fmul g27, g27, g31
    g.fli g31, 1.0
    g.fsub g27, g27, g31
    g.li g30, 1
    g.sub g28, g1, g30
    g.li g31, 16
    g.shr g30, g28, g31
    g.xor g28, g28, g30
    g.li g31, 0x7feb352d
    g.mul g28, g28, g31
    g.li g31, 15
    g.shr g30, g28, g31
    g.xor g28, g28, g30
    g.li g31, 0x846ca68b
    g.mul g28, g28, g31
    g.li g31, 16
    g.shr g30, g28, g31
    g.xor g28, g28, g30
    g.li g31, 65535
    g.and g28, g28, g31
    g.itof g28, g28
    g.fli g31, 0.000030517578125
    g.fmul g28, g28, g31
    g.fli g31, 1.0
    g.fsub g28, g28, g31
    ; Snare/clap on beats 2 and 4, with a finite decay.
    g.mov g21, g0
    g.li g30, 1
    g.and g30, g8, g30
    g.bz g30, snare_done
    g.fadd g21, g27, g28
    g.fli g30, 0.5
    g.fmul g21, g21, g30
    g.fli g30, 0.30
    g.fdiv g30, g24, g30
    g.fli g31, 1.0
    g.fsub g30, g31, g30
    g.fmax g30, g30, g0
    g.fmul g30, g30, g30
    g.fmul g21, g21, g30
    g.fli g30, 0.20        ; SNARE_GAIN
    g.fmul g21, g21, g30
snare_done:
    ; Offbeat hats use the high-pass hash difference and short envelope.
    g.mov g22, g0
    g.bz g7, hat_done
    g.fsub g22, g27, g28
    g.fli g30, 0.5
    g.fmul g22, g22, g30
    g.fli g30, 0.40
    g.fdiv g30, g6, g30
    g.fli g31, 1.0
    g.fsub g30, g31, g30
    g.fmax g30, g30, g0
    g.fmul g30, g30, g30
    g.fmul g30, g30, g30
    g.fmul g22, g22, g30
    g.fli g30, 0.09        ; HAT_GAIN
    g.fmul g22, g22, g30
hat_done:
    ; Drum entry marks the arrangement: hats in bars 0-1, partial kick in
    ; bar 2, a two-eighth drum gap at the end of bar 3, then the full drop.
    g.li g30, 2
    g.sltu g31, g9, g30
    g.bz g31, drum_bar2
    g.mov g20, g0
    g.mov g21, g0
    g.fli g11, 1.0       ; no invisible kick ducking during the intro
    g.jmp drums_arranged
drum_bar2:
    g.li g30, 3
    g.sltu g31, g9, g30
    g.bz g31, drum_bar3
    g.fli g30, 0.62
    g.fmul g20, g20, g30
    g.fmul g21, g21, g30
    g.jmp drums_arranged
drum_bar3:
    g.li g30, 4
    g.sltu g31, g9, g30
    g.bz g31, drums_arranged
    g.li g30, 7
    g.and g31, g5, g30
    g.li g30, 6
    g.sltu g31, g31, g30
    g.bnz g31, drums_arranged
    g.mov g20, g0
    g.mov g21, g0
    g.mov g22, g0
    g.fli g11, 1.0
drums_arranged:
    ; Rise through four build bars, then hit full level for four drop bars.
    g.li g30, 4
    g.sltu g31, g9, g30
    g.bz g31, full_drop
    g.itof g30, g9
    g.fli g31, 0.13
    g.fmul g30, g30, g31
    g.fli g31, 0.35
    g.fadd g30, g30, g31
    g.jmp arrangement_ready
full_drop:
    g.fli g30, 1.0
arrangement_ready:
    g.fmul g18, g18, g11
    g.fmul g29, g29, g11
    g.fmul g19, g19, g11
    g.fmul g23, g23, g11
    g.fmul g18, g18, g30
    g.fmul g29, g29, g30
    g.fmul g19, g19, g30
    g.fmul g20, g20, g30
    g.fmul g21, g21, g30
    g.fmul g22, g22, g30
    g.fmul g23, g23, g30
    ; Deterministic stereo mix with wide riff and centred low end.
    g.mov g25, g18
    g.mov g26, g29
    g.fli g30, 0.80
    g.fmul g31, g19, g30
    g.fadd g25, g25, g31
    g.fadd g26, g26, g31
    g.fli g30, 0.90
    g.fmul g31, g23, g30
    g.fadd g25, g25, g31
    g.fadd g26, g26, g31
    g.fli g30, 0.85
    g.fmul g31, g20, g30
    g.fadd g25, g25, g31
    g.fadd g26, g26, g31
    g.fli g30, 0.70
    g.fmul g31, g21, g30
    g.fadd g25, g25, g31
    g.fli g30, 0.85
    g.fmul g31, g21, g30
    g.fadd g26, g26, g31
    g.fli g30, 0.70
    g.fmul g31, g22, g30
    g.fadd g25, g25, g31
    g.fli g30, 0.55
    g.fmul g31, g22, g30
    g.fadd g26, g26, g31
    ; One-block master fade-in protects the first sample of a fresh load.
    g.fli g30, 0.00390625
    g.fmul g30, g3, g30
    g.fli g31, 1.0
    g.fmin g30, g30, g31
    g.fmul g25, g25, g30
    g.fmul g26, g26, g30
    g.li g27, 3
    g.shl g27, g2, g27
    g.st g25, g27, 0
    g.li g30, 4
    g.add g27, g27, g30
    g.st g26, g27, 0
    g.end
sound_kernel_end:

sound_tables:
supersaw_voices:
    ; detune, left weight, right weight, phase; seven saws spread +/-4.5%.
    .float 0.955, 0.19, 0.04, 0.00
    .float 0.970, 0.18, 0.07, 0.13
    .float 0.986, 0.14, 0.10, 0.27
    .float 1.000, 0.14, 0.14, 0.41
    .float 1.014, 0.10, 0.14, 0.55
    .float 1.030, 0.07, 0.18, 0.69
    .float 1.045, 0.04, 0.19, 0.83
    ; Phase cycles per 11,250-sample eighth (15/64 s at 48 kHz).
lead_riff:
    ; 64 eighth rows: f32 cycles/eighth, then packed u32 start+duration*256.
    ; bar 0: E3(4), B3(2), G3(2)
    .float 38.62823435
    .word 1024
    .float 38.62823435
    .word 1024
    .float 38.62823435
    .word 1024
    .float 38.62823435
    .word 1024
    .float 57.87694920
    .word 516
    .float 57.87694920
    .word 516
    .float 45.93696095
    .word 518
    .float 45.93696095
    .word 518
    ; bar 1: C4(3), G3(3), rest(2)
    .float 61.31848830
    .word 776
    .float 61.31848830
    .word 776
    .float 61.31848830
    .word 776
    .float 45.93696095
    .word 779
    .float 45.93696095
    .word 779
    .float 45.93696095
    .word 779
    .float 0.00000000
    .word 0
    .float 0.00000000
    .word 0
    ; bar 2: G3(4), D4(2), B3(2)
    .float 45.93696095
    .word 1040
    .float 45.93696095
    .word 1040
    .float 45.93696095
    .word 1040
    .float 45.93696095
    .word 1040
    .float 68.82767580
    .word 532
    .float 68.82767580
    .word 532
    .float 57.87694920
    .word 534
    .float 57.87694920
    .word 534
    ; bar 3: D4(3), A3(3), rest(2)
    .float 68.82767580
    .word 792
    .float 68.82767580
    .word 792
    .float 68.82767580
    .word 792
    .float 51.56250000
    .word 795
    .float 51.56250000
    .word 795
    .float 51.56250000
    .word 795
    .float 0.00000000
    .word 0
    .float 0.00000000
    .word 0
    ; bar 4: E4(4), B3(2), G3(2)
    .float 77.25645705
    .word 1056
    .float 77.25645705
    .word 1056
    .float 77.25645705
    .word 1056
    .float 77.25645705
    .word 1056
    .float 57.87694920
    .word 548
    .float 57.87694920
    .word 548
    .float 45.93696095
    .word 550
    .float 45.93696095
    .word 550
    ; bar 5: C4(3), G3(3), rest(2)
    .float 61.31848830
    .word 808
    .float 61.31848830
    .word 808
    .float 61.31848830
    .word 808
    .float 45.93696095
    .word 811
    .float 45.93696095
    .word 811
    .float 45.93696095
    .word 811
    .float 0.00000000
    .word 0
    .float 0.00000000
    .word 0
    ; bar 6: G3(4), D4(2), B3(2)
    .float 45.93696095
    .word 1072
    .float 45.93696095
    .word 1072
    .float 45.93696095
    .word 1072
    .float 45.93696095
    .word 1072
    .float 68.82767580
    .word 564
    .float 68.82767580
    .word 564
    .float 57.87694920
    .word 566
    .float 57.87694920
    .word 566
    ; bar 7: D4(3), A3(3), rest(2)
    .float 68.82767580
    .word 824
    .float 68.82767580
    .word 824
    .float 68.82767580
    .word 824
    .float 51.56250000
    .word 827
    .float 51.56250000
    .word 827
    .float 51.56250000
    .word 827
    .float 0.00000000
    .word 0
    .float 0.00000000
    .word 0
    ; Phase cycles per 22,500-sample quarter (15/32 s at 48 kHz).
bass_line:
    .float 77.2564687, 115.7539219, 77.2564687, 0.0000000
    .float 61.3185000, 91.8739219, 61.3185000, 0.0000000
    .float 91.8739219, 68.8276875, 91.8739219, 0.0000000
    .float 68.8276875, 103.1250000, 68.8276875, 0.0000000
    .float 77.2564687, 115.7539219, 77.2564687, 0.0000000
    .float 61.3185000, 91.8739219, 61.3185000, 0.0000000
    .float 91.8739219, 68.8276875, 91.8739219, 0.0000000
    .float 68.8276875, 103.1250000, 68.8276875, 0.0000000
chord_progression:
    .float 77.2564687, 91.8739219
    .float 61.3185000, 77.2564687
    .float 45.9369609, 57.8769609
    .float 68.8276875, 86.7174375
    .float 77.2564687, 91.8739219
    .float 61.3185000, 77.2564687
    .float 45.9369609, 57.8769609
    .float 68.8276875, 86.7174375
sound_tables_end:
