// Publishes the Cartridges page, Studio and cartridge notes from design/ into web/ for deployment.
// web/index.html is the cartridge shelf, web/studio.html the viewer (driven by the unchanged web/app.js), web/notes.html
// an author's notes, and web/previews/ holds only the posters, GIFs, scene keyframes, cartridge sources, notes and a slim data file.
// Usage: node design/tools/publish-web.mjs   (after design/tools/make-previews.mjs)
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const design = resolve(root, 'design'), previews = resolve(design, 'previews'), web = resolve(root, 'web');
const ORDER = ['daybreak', 'pelican', 'limit-set', 'elsewhere', 'lightcone', 'astra', 'supersaw', 'carpet', 'aurora', 'rgb-study', 'ray-tracer', 'ray-tracer-r1', 'gpu-ray-tracer', 'gpu-ray-tracer-fast', 'signal-garden', 'neon-stadium'];

function page(from, to, replacements) {
  let html = readFileSync(resolve(design, from), 'utf8');
  for (const [pattern, value] of replacements) {
    if (!html.includes(pattern)) throw new Error(`${from}: expected "${pattern}"; update publish-web.mjs`);
    html = html.replaceAll(pattern, value);
  }
  writeFileSync(resolve(web, to), html);
}
const common = [['<script src="switcher.js"></script>\n', ''], ['href="console.html"', 'href="./"']];
page('console.html', 'index.html', [...common, ["'../web/audio-player.js'", "'./audio-player.js'"], ["'../web/machine-worker.js'", "'./machine-worker.js'"],
  ["'../web/backdrop-worker.js'", "'./backdrop-worker.js'"]]);
page('studio.html', 'studio.html', [...common, ['src="../web/app.js"', 'src="./app.js"'], ['value="../design/previews/src/', 'value="previews/src/']]);
page('notes.html', 'notes.html', [...common, ["const SHELF = 'console.html'", "const SHELF = './'"]]);

const out = resolve(web, 'previews');
rmSync(out, { recursive: true, force: true });
mkdirSync(resolve(out, 'src'), { recursive: true });
mkdirSync(resolve(out, 'notes'), { recursive: true });
const records = ORDER.map((id) => JSON.parse(readFileSync(resolve(previews, 'records', `${id}.json`), 'utf8')));
const copy = (file) => copyFileSync(resolve(previews, file), resolve(out, file));
for (const r of records) {
  copy(r.poster); copy(r.gif);
  if (r.scenes) r.keyframes.forEach((k) => copy(k.file));
  // the exact source of every cartridge (including transformed variants), loaded by the shelf's player and the Studio
  if (!existsSync(resolve(previews, 'src', `${r.id}.asm`))) throw new Error(`Missing design/previews/src/${r.id}.asm; run make-previews.mjs`);
  copy(`src/${r.id}.asm`);
  if (r.readme) copy(r.readme); // the author's notes, rendered by notes.html
}
// frames cycled by the homepage's machine diagram that are not already part of a scene strip
for (const file of ['pelican-k01.png', 'pelican-k05.png']) copy(file);
const slim = records.map((r) => ({
  id: r.id, title: r.title, subtitle: r.subtitle, author: r.author, description: r.description, notes: r.notes.slice(0, 1),
  profile: r.profile, format: r.format, engines: r.engines, payloadBytes: r.payloadBytes, lines: r.lines, seconds: r.seconds,
  scenes: r.scenes, audio: Boolean(r.audio), poster: r.poster, gif: r.gif, keyframes: r.scenes ? r.keyframes : [], readme: r.readme ?? null,
}));
writeFileSync(resolve(out, 'data.js'), `// Generated by design/tools/publish-web.mjs from the reference-machine captures.\nwindow.DEMOS = ${JSON.stringify(slim)};\n`);
console.log(`Published index.html, studio.html and ${records.length} cartridges to web/`);
