; Signal Garden: a self-contained audio-clocked compute demo.
; The SPU only schedules a generic g.* kernel. Guest instructions implement
; wavetable interpolation, three melodic voices, a bass, a two-tap noise FIR,
; envelopes, panning, and the final interleaved stereo floating-point stores.
; The CPU paints a small indexed visual and animates one scanline at vblank.
.profile spu-1
.equ SPU, 0xf6000
.equ VIDEO, 0xf5000
.equ FB, 0x10000
.equ PAL, 0x20000
.equ AUDIO, 0x24000
.entry start

start:
    li r12, SPU
    li r1, sound_kernel
    sw r1, 0x40(r12)
    li r1, sound_kernel_end-sound_kernel
    sw r1, 0x44(r12)
    li r1, 128
    sw r1, 0x48(r12)
    li r1, 2
    sw r1, 0x4c(r12)
    li r1, AUDIO
    sw r1, 0x50(r12)
    sw r1, 0x100(r12)       ; binding 0: 256 stereo f32 sample frames
    li r1, 2048
    sw r1, 0x104(r12)
    li r1, 3
    sw r1, 0x108(r12)
    li r1, sound_tables
    sw r1, 0x110(r12)       ; binding 1: counted ROM wavetables/notes
    li r1, sound_tables_end-sound_tables
    sw r1, 0x114(r12)
    li r1, 1
    sw r1, 0x118(r12)
    sw r1, 0(r12)           ; enable audio before visual setup

    ; A 256-colour blue-to-coral palette, generated by the guest CPU.
    li r2, PAL
    mov r3, r0
    li r4, 256
    li r5, 1
palette_loop:
    addi r6, r3, 24
    sb r6, 0(r2)
    shr r7, r3, r5
    addi r7, r7, 70
    sb r7, 1(r2)
    sub r8, r4, r3
    sb r8, 2(r2)
    addi r2, r2, 3
    addi r3, r3, 1
    bltu r3, r4, palette_loop

    ; Interference stripes and a bright centre band in the I8 framebuffer.
    li r2, FB
    mov r3, r0             ; y
    li r10, 120
    li r11, 160
paint_row:
    mov r4, r0             ; x
paint_pixel:
    li r5, 2
    shl r6, r3, r5
    xor r6, r6, r4
    andi r6, r6, 127
    li r5, 52
    bltu r3, r5, paint_store
    li r5, 68
    bltu r3, r5, paint_centre
    j paint_store
paint_centre:
    addi r6, r6, 90
paint_store:
    sb r6, 0(r2)
    addi r2, r2, 1
    addi r4, r4, 1
    bltu r4, r11, paint_pixel
    addi r3, r3, 1
    bltu r3, r10, paint_row

    li r9, VIDEO
    li r1, FB
    sw r1, 0(r9)
    li r1, 160
    sw r1, 4(r9)
    li r1, 3              ; I8, 256-colour palette
    sw r1, 8(r9)
    li r1, PAL
    sw r1, 12(r9)
    li r1, 1
    sw r1, 16(r9)
    sw r1, 20(r9)
    mov r8, r0             ; visual phase
visual_frame:
    wfi
    li r2, FB+9600        ; middle scanline, y=60
    mov r3, r0
    li r4, 160
visual_pixel:
    add r5, r3, r8
    andi r5, r5, 255
    sb r5, 0(r2)
    addi r2, r2, 1
    addi r3, r3, 1
    bltu r3, r4, visual_pixel
    addi r8, r8, 3
    j visual_frame

; Register map: g1 absolute sample index; g2 invocation index; g3 sample
; time as f32; g4..6 beat count/index/phase; g7 note; g18 lead;
; g19 bass; g20 percussion; g28 chord pad; g25/26 stereo accumulators.
sound_kernel:
    g.uniform g1, 14
    g.id g2, 2
    g.add g1, g1, g2
    g.itof g3, g1
    g.uniform g30, 15
    g.itof g30, g30
    g.fli g31, 0.125
    g.fmul g30, g30, g31       ; samples per eighth-note = rate / 8
    g.fdiv g4, g3, g30
    g.ftoi g5, g4
    g.itof g6, g5
    g.fsub g6, g4, g6          ; fractional position in this beat
    g.li g7, 7
    g.and g7, g5, g7          ; eight-note arpeggio
    g.li g8, 2
    g.shl g8, g7, g8
    g.li g9, 64
    g.add g8, g8, g9
    g.ld g9, g8, 1            ; cycles per beat from guest ROM

    ; Lead oscillator: linear interpolation in a 16-point sine wavetable.
    g.fmul g12, g6, g9
    g.ftoi g13, g12
    g.itof g14, g13
    g.fsub g12, g12, g14      ; wrap phase into [0,1)
    g.fli g13, 16.0
    g.fmul g12, g12, g13
    g.ftoi g13, g12          ; table index 0..15
    g.itof g14, g13
    g.fsub g17, g12, g14     ; interpolation fraction
    g.li g14, 2
    g.shl g14, g13, g14
    g.ld g15, g14, 1
    g.li g16, 1
    g.add g16, g13, g16
    g.li g14, 15
    g.and g16, g16, g14
    g.li g14, 2
    g.shl g16, g16, g14
    g.ld g16, g16, 1
    g.fsub g16, g16, g15
    g.fmul g16, g16, g17
    g.fadd g18, g15, g16
    ; Fast attack and quadratic decay end near zero at the next note.
    g.fli g10, 0.04
    g.fdiv g11, g6, g10
    g.fli g10, 1.0
    g.fmin g11, g11, g10
    g.fsub g10, g10, g6
    g.fmul g10, g10, g10
    g.fmul g11, g11, g10
    g.fmul g18, g18, g11
    g.fli g10, 0.42
    g.fmul g18, g18, g10

    ; Bass C3, a triangle derived from phase arithmetic. The same explicit
    ; arithmetic below creates two simultaneous chord tones, C4 and E4.
    g.uniform g31, 15
    g.itof g31, g31
    g.fli g21, 130.8128
    g.fdiv g21, g21, g31
    g.fmul g21, g3, g21
    g.ftoi g22, g21
    g.itof g22, g22
    g.fsub g21, g21, g22
    g.fli g22, 0.5
    g.fsub g21, g21, g22
    g.fsub g22, g0, g21
    g.fmax g21, g21, g22
    g.fli g22, 4.0
    g.fmul g21, g21, g22
    g.fli g22, 1.0
    g.fsub g19, g22, g21
    g.fli g22, 0.17
    g.fmul g19, g19, g22

    g.fli g21, 261.6256
    g.fdiv g21, g21, g31
    g.fmul g21, g3, g21
    g.ftoi g22, g21
    g.itof g22, g22
    g.fsub g21, g21, g22
    g.fli g22, 0.5
    g.fsub g21, g21, g22
    g.fsub g22, g0, g21
    g.fmax g21, g21, g22
    g.fli g22, 4.0
    g.fmul g21, g21, g22
    g.fli g22, 1.0
    g.fsub g28, g22, g21
    g.fli g22, 0.055
    g.fmul g28, g28, g22

    g.fli g21, 329.6276
    g.fdiv g21, g21, g31
    g.fmul g21, g3, g21
    g.ftoi g22, g21
    g.itof g22, g22
    g.fsub g21, g21, g22
    g.fli g22, 0.5
    g.fsub g21, g21, g22
    g.fsub g22, g0, g21
    g.fmax g21, g21, g22
    g.fli g22, 4.0
    g.fmul g21, g21, g22
    g.fli g22, 1.0
    g.fsub g23, g22, g21
    g.fli g22, 0.055
    g.fmul g23, g23, g22
    g.fadd g28, g28, g23

    ; A percussive voice from two adjacent integer-hash samples. Averaging
    ; them is an explicit two-tap FIR low-pass filter, then a fourth-power
    ; beat envelope turns the filtered noise into short hats.
    g.li g21, 1664525
    g.mul g22, g1, g21
    g.li g23, 1013904223
    g.add g22, g22, g23
    g.li g24, 24
    g.shr g22, g22, g24
    g.li g25, 1
    g.sub g25, g1, g25
    g.mul g25, g25, g21
    g.add g25, g25, g23
    g.shr g25, g25, g24
    g.add g22, g22, g25
    g.itof g20, g22
    g.fli g21, 255.0
    g.fsub g20, g20, g21
    g.fli g21, 0.0039215686
    g.fmul g20, g20, g21
    g.fli g21, 1.0
    g.fsub g21, g21, g6
    g.fmul g21, g21, g21
    g.fmul g21, g21, g21
    g.fli g22, 0.09
    g.fmul g21, g21, g22
    g.fmul g20, g20, g21

    ; Centre the chord and bass. Move the melody left/right on alternating
    ; notes, with slightly different percussion level in each channel.
    g.fli g21, 0.65
    g.fmul g25, g19, g21
    g.mov g26, g25
    g.fadd g25, g25, g28
    g.fadd g26, g26, g28
    g.fli g21, 0.7
    g.fmul g22, g20, g21
    g.fadd g25, g25, g22
    g.fli g21, 0.4
    g.fmul g22, g20, g21
    g.fadd g26, g26, g22
    g.li g21, 1
    g.and g21, g7, g21
    g.bz g21, lead_left
    g.fli g21, 0.40
    g.fmul g22, g18, g21
    g.fadd g25, g25, g22
    g.fli g21, 0.75
    g.fmul g22, g18, g21
    g.fadd g26, g26, g22
    g.jmp store_stereo
lead_left:
    g.fli g21, 0.75
    g.fmul g22, g18, g21
    g.fadd g25, g25, g22
    g.fli g21, 0.40
    g.fmul g22, g18, g21
    g.fadd g26, g26, g22
store_stereo:
    ; One-block start ramp removes the otherwise abrupt DC step at sample 0.
    g.fli g21, 0.00390625
    g.fmul g21, g3, g21
    g.fli g22, 1.0
    g.fmin g21, g21, g22
    g.fmul g25, g25, g21
    g.fmul g26, g26, g21
    g.li g27, 3
    g.shl g27, g2, g27
    g.st g25, g27, 0
    g.li g29, 4
    g.add g27, g27, g29
    g.st g26, g27, 0
    g.end
sound_kernel_end:

sound_tables:
    .float 0.0, 0.38268343, 0.70710678, 0.92387953
    .float 1.0, 0.92387953, 0.70710678, 0.38268343
    .float 0.0, -0.38268343, -0.70710678, -0.92387953
    .float -1.0, -0.92387953, -0.70710678, -0.38268343
    ; C5 E5 G5 C6 G5 E5 D5 B4, cycles per eighth-note.
    .float 65.4064, 82.4069, 98.0, 130.8128
    .float 98.0, 82.4069, 73.4162, 61.7354
sound_tables_end:
