import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { createMachine, WIDTH, HEIGHT } from './wasm-host.mjs';
import { png } from './png.mjs';
const args=process.argv.slice(2);
const option=(name,fallback)=> { const at=args.indexOf(name); return at<0?fallback:args[at+1]; };
const demo=option('--demo','aurora');
const frames=Number(option('--frames','120'));
if (!Number.isInteger(frames)||frames<1||frames>36000) throw new Error('--frames must be 1..36000');
const source=option('--source',`examples/${demo}.asm`);
const out=resolve(option('--out',`artifacts/${demo}.png`));
const machine=createMachine();
const cartridge=machine.assemble(readFileSync(source,'utf8'));
machine.load(cartridge); machine.runFrames(frames);
mkdirSync(dirname(out),{recursive:true});
writeFileSync(out,png(WIDTH,HEIGHT,machine.frame()));
writeFileSync(out.replace(/\.png$/i,'')+'.db32',cartridge);
writeFileSync(out.replace(/\.png$/i,'')+'.json',JSON.stringify({...machine.info(),source,host:process.version},null,2)+'\n');
console.log(JSON.stringify({...machine.info(),image:out},null,2));
